
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ST = 32;
  public static final int LOCATION_PRECEDENCE = 49;
  public static final int MULT = 42;
  public static final int EQUALS = 34;
  public static final int INTEGER = 45;
  public static final int CONTINUE = 5;
  public static final int INT = 8;
  public static final int BTE = 35;
  public static final int MINUS = 41;
  public static final int STE = 36;
  public static final int LSP = 25;
  public static final int STATIC = 13;
  public static final int AND = 38;
  public static final int NOT = 33;
  public static final int OR = 39;
  public static final int LP = 21;
  public static final int COMMA = 28;
  public static final int CLASS = 4;
  public static final int DIV = 43;
  public static final int RP = 22;
  public static final int PLUS = 40;
  public static final int ASSIGN = 30;
  public static final int IF = 10;
  public static final int THIS = 15;
  public static final int ID = 46;
  public static final int DOT = 29;
  public static final int LCP = 24;
  public static final int BOOLEAN = 2;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int TRUE = 18;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int BT = 31;
  public static final int RSP = 26;
  public static final int NULL = 20;
  public static final int MOD = 44;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int ELSE = 6;
  public static final int TYPE_STRING = 17;
  public static final int WHILE = 14;
  public static final int CLASS_ID = 47;
  public static final int RCP = 23;
  public static final int NE = 37;
  public static final int EXTENDS = 7;
  public static final int STRING = 48;
  public static final int CALL_PRECEDENCE = 50;
  public static final int FALSE = 19;
  public static final int LENGTH = 16;
  public static final int SEMI_COLONS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "ELSE",
  "EXTENDS",
  "INT",
  "NEW",
  "IF",
  "RETURN",
  "VOID",
  "STATIC",
  "WHILE",
  "THIS",
  "LENGTH",
  "TYPE_STRING",
  "TRUE",
  "FALSE",
  "NULL",
  "LP",
  "RP",
  "RCP",
  "LCP",
  "LSP",
  "RSP",
  "SEMI_COLONS",
  "COMMA",
  "DOT",
  "ASSIGN",
  "BT",
  "ST",
  "NOT",
  "EQUALS",
  "BTE",
  "STE",
  "NE",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "INTEGER",
  "ID",
  "CLASS_ID",
  "STRING",
  "LOCATION_PRECEDENCE",
  "CALL_PRECEDENCE"
  };
}

